### ISSUE TITLE
卻 not refer to "cia" 

### ISSUE THREAD

**Issue by ZWolken** [pearapple123/rime-iuciou#2]
In `iuciou.dict.yaml` the dictionary file, 卻 refers to "cia", but infact it pronounce "tɕ'ia" which I think is "chia".
By the way, may I know where this character's pronoounce from?
I want to create a dictionary file depends on Shen & Shen's romanisation work, but I can't found any files that are already made by others.

**Comment by pearapple123** [comment]
Apologies, I made this a long time ago and have since moved on from Sinitic languages and making IMEs. I got my romanisations from scraping a site called [wugniu.com](https://wugniu.com/) but checking now I see that 卻 hasn't been recorded in their 温州话 database so  I'm not sure where I got my reading from. Incidentally their 永嘉话 database says 卻 is pronounced "tɕʰia" so it agrees with you.

**Comment by ZWolken** [comment]
Never mind.
Also, during this period, I made another Wenzhounese input method based on Rime.
Just check [rime-wenzhounese](https://github.com/ZWolken/rime-wenzhounese) if you want.
This pronunciation or spelling is from Shen-Shen(沈克成-沈迦), which is  probably a more modern spelling system.
